#!/bin/bash

# choose from a list of items output by $1, sends as input to $2
# runs st in the background in order to start faster
# depends on jhawthorn/fzy and syrrim/st 

DAEMON="/tmp/choose_daemon_$1"

if [[ -e "$DAEMON" ]]; then 
    kill -SIGRTMIN $(cat "$DAEMON")
else
    bash -c "st -m bar -h 5 sh -c \"$1 | fzy 1>&3\" 3>&1 | $2"
fi

nohup sh -c "st -m bar -h 5 -k \"$DAEMON\" sh -c \"$1 | fzy 1>&3\" 3>&1 | $2" &>/dev/null 0<&- &
